DROP TABLE IF EXISTS PUBLIC.USERS;

CREATE TABLE IF NOT EXISTS PUBLIC.USERS(
  id SERIAL PRIMARY KEY,
  username TEXT UNIQUE,
  password_hash TEXT
);

-- DROP TABLE IF EXISTS PUBLIC.PRODUCT;

-- CREATE TABLE IF NOT EXISTS PUBLIC.PRODUCT(
--   id uint PRIMARY KEY,
--   username TEXT UNIQUE,
--   password_hash TEXT
-- );